import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByText('Countdown to next event:').click();
  await page.getByRole('main').getByRole('link', { name: 'Home' }).click();
  await expect(page).toHaveTitle('Home');
  await page.getByRole('main').getByRole('link', { name: 'Drivers' }).click();
  await expect(page).toHaveTitle('Drivers');
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page).toHaveTitle('Home');
  await page.getByRole('main').getByRole('link', { name: 'Track info' }).click();
  await expect(page).toHaveTitle('Track Info');
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page).toHaveTitle('Home');
  await page.getByRole('main').getByRole('link', { name: 'Lap Times' }).click();
  await expect(page).toHaveTitle('Lap Times');
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page).toHaveTitle('Home');
  await page.getByRole('main').getByRole('link', { name: 'Race Leaderboard' }).click();
  await expect(page).toHaveTitle('Race Leaderboard');
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page).toHaveTitle('Home');
  await page.getByRole('main').getByRole('link', { name: 'Pit Stops' }).click();
  await expect(page).toHaveTitle('Pit Stops');
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page).toHaveTitle('Home');
  await page.getByRole('main').getByRole('link', { name: 'Single Driver' }).click();
  await expect(page).toHaveTitle('Single Driver');
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page).toHaveTitle('Home');
  await page.getByRole('main').getByRole('link', { name: 'Race Control' }).click();
  await expect(page).toHaveTitle('Race Control');
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page).toHaveTitle('Home');
  await page.getByRole('main').getByRole('link', { name: 'Team Radio' }).click();
  await expect(page).toHaveTitle('Team Radio');
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page).toHaveTitle('Home');
  await page.getByRole('main').getByRole('link', { name: 'GP List' }).click();
  await expect(page).toHaveTitle('GP List');
  await page.getByRole('link', { name: 'Home' }).click();
  await expect(page).toHaveTitle('Home');
});