name: Start EC2 Instance

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  manage-ec2:
    runs-on: ubuntu-latest
    environment: aws_ec2_1
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Start EC2 Instance
      run: aws ec2 start-instances --instance-ids i-00706e63dfd336599
