# name: Start or stop EC2 Instance

# on:
#   workflow_dispatch:
#     inputs:
#       action:
#         description: 'Start or Stop EC2'
#         required: true
#         default: 'start'
#         type: choice
#         options:
#           - start
#           - stop

# permissions:
#   contents: read
#   id-token: write

# jobs:
#   manage-ec2:
#     runs-on: ubuntu-latest
#     environment: aws_ec2_1
#     steps:
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v2
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: eu-north-1

#     - name: Start or Stop EC2 Instance
#       run: |
#         if [ "${{ github.event.inputs.action }}" = "start" ]; then
#           aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
#         elif [ "${{ github.event.inputs.action }}" = "stop" ]; then
#           aws ec2 stop-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
#         fi
